# backwards configuration, the robot will move backwards
ForwardLocalPlanner:
    k_rho: 1.0
    k_alpha: -0.4
    k_betta: -1.0
    carrot_distance: 0.8 #meters
    carrot_angular_distance: 0.5 # radians, no constraint, max 3.1416
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.157