language: generic
services:
  - docker

env:
  global:
    DOCKER_RUN_OPTS='-e GITHUB_TOKEN -e TRAVIS_BRANCH -e TRAVI_REPO_SLUG' 
    AFTER_SCRIPT=./gh-pages.sh
    CATKIN_CONFIG=--no-install
  matrix:
    - ROS_DISTRO="melodic" NOT_TEST_BUILD=true

install:
  - git clone --depth 1 https://github.com/ridgeback/ridgeback.git ridgeback
  - git clone --depth 1 https://github.com/ros-perception/slam_gmapping.git gmapping
  - git clone --depth 1 https://github.com/ros-visualization/interactive_marker_twist_server.git
  - git clone --depth 1 https://github.com/clearpathrobotics/LMS1xx.git --branch melodic_devel
  - git clone --depth 1 https://github.com/ros-perception/openslam_gmapping.git
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
  - git clone --quiet --depth 1 https://github.com/ros-infrastructure/rosdoc_lite
script:
  - .industrial_ci/travis.sh
