language: generic
services:
  - docker

env:
  - ROS_DISTRO="melodic" NOT_TEST_BUILD=true

install:
  - git clone --depth 1 https://github.com/ridgeback/ridgeback.git ridgeback
  - git clone --depth 1 https://github.com/ros-perception/slam_gmapping.git gmapping
  - git clone --depth 1 https://github.com/ros-visualization/interactive_marker_twist_server.git
  - git clone --depth 1 https://github.com/clearpathrobotics/LMS1xx.git --branch melodic_devel
  - git clone --depth 1 https://github.com/ros-perception/openslam_gmapping.git
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
after_success: after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.

    git clone https://pabloinigoblasco:$GITHUB_TOKEN@github.com/reelrbtx/smacc --branch gh-pages doc

    cd doc
    git rm -r $TRAVIS_BRANCH/$TRAVI_REPO_SLUG >/dev/null
    mkdir -p $TRAVIS_BRANCH/$TRAVI_REPO_SLUG

    #git init
    #git checkout -b gh-pages
    cd $TRAVIS_BRANCH/$TRAVI_REPO_SLUG
    rosdoc_lite `rospack find smacc` -o smacc
    rosdoc_lite `rospack find smacc_tool_plugin_template` -o smacc_tool_plugin_template
    rosdoc_lite `rospack find backward_global_planner` -o backward_global_planner
    rosdoc_lite `rospack find backward_local_planner` -o backward_local_planner
    rosdoc_lite `rospack find forward_global_planner` -o forward_global_planner
    rosdoc_lite `rospack find forward_local_planner` -o forward_local_planner
    rosdoc_lite `rospack find smacc_navigation_plugin` -o smacc_navigation_plugin
    rosdoc_lite `rospack find smacc_odom_tracker` -o smacc_odom_tracker
    rosdoc_lite `rospack find smacc_planner_switcher` -o smacc_planner_switcher
    rosdoc_lite `rospack find radial_motion_example` -o radial_motion_example

    git add .

    git -c user.name='travis' -c user.email='travis' commit -q -m "gh-pages travis"
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://pabloinigoblasco:$GITHUB_TOKEN@github.com/reelrbtx/smacc gh-pages&>/dev/null
    cd "$TRAVIS_BUILD_DIR"

  fi