# backwards configuration, the robot will move backwards
RetractingLocalPlanner:
    k_rho: -0.6
    k_alpha: -0.5
    k_betta: -1.0
    alpha_offset: 3.1416
    betta_offset: 0.0
    carrot_distance: 0.005 #meters
    carrot_angular_distance: 4 # no constraint, max 3.1416
    xy_goal_tolerance: 0.04
    yaw_goal_tolerance: 0.3