# backwards configuration, the robot will move backwards
BackwardLocalPlanner:
    k_rho: -0.6
    k_alpha: -1
    k_betta: 0#-1.0
    carrot_distance: 0.5 #meters
    carrot_angular_distance: 0.15
    xy_goal_tolerance: 0.04
    yaw_goal_tolerance: 0.3
    pure_spinning_straight_line_mode: false