joint_states:
  torso_lift_joint: 0.35
  bellows_joint: 0.06
  head_pan_joint: 0.00
  head_tilt_joint: 0.00
  shoulder_pan_joint: 1.45
  shoulder_lift_joint: 1.52
  upperarm_roll_joint: -0.10
  elbow_flex_joint : 1.64
  forearm_roll_joint: 0.00
  wrist_flex_joint: 1.61
  wrist_roll_joint: 0.0
  l_gripper_finger_joint: 0.00
  r_gripper_finger_joint: 0.00